apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: two-tier
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shivasimha/letskonnect-server:1
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: PORT
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_DB
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
