apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: two-tier
  labels:
    app: backend

type: Opaque
data:
  PORT: NDAwMA==
  MONGO_DB: bW9uZ29kYitzcnY6Ly9zaGl2YXNpbWhhMDc6ZGV2ZWxvcGVyMDc2M0Brb25uZWN0Y2x1c3Rlci5peWJzamhmLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1rb25uZWN0Y2x1c3Rlcgo= 
  JWT_SECRET: Tzh3ZkM3aFpIbmxOYkIzeFVybXVLRXpDQ1lQYU00bjQxaEg3d1BwNnRRWms3RnRrOTR0NjBxU29RWGE5Si9JNgpvZTNFbHVwWTV2MlZ5OVZsMEVCRzRnPT0=
