apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
  labels:
    app: backend

type: Opaque
data:
  PORT: NDAwMA==
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9kZXZlbG9wOmRldmVsb3AxMjNAZS1jb21tZXJjZS5yMmNiN3k4Lm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  JWT_SECRET: Tzh3ZkM3aFpIbmxOYkIzeFVybXVLRXpDQ1lQYU00bjQxaEg3d1BwNnRRWms3RnRrOTR0NjBxU29RWGE5Si9JNgpvZTNFbHVwWTV2MlZ5OVZsMEVCRzRnPT0=
