apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: two-tier
  labels:
    app: backend

type: Opaque
stringData:
  MONGO_DB: "bW9uZ29kYitzcnY6Ly9rb25uZWN0aGVyZTpuYW5pMDc2M0Brb25uZWN0Y2x1c3Rlci5peWJzamhmLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1rb25uZWN0Y2x1c3Rlcgo="
  JWT_SECRET: "LsI4Sc5+hfvmgvIPq7RUzyP2xfLi+Witic49FIQ4sX1jfZ3xEdfRvjJb9AIP5Drie3DZm6RKVB+khZ1e1kWpcw=="
  PORT: "4000"
