apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: two-tier
  labels:
    app: backend

type: Opaque
stringData:
  MONGO_DB= "mongodb+srv://konnecthere:nani0763@konnectcluster.iybsjhf.mongodb.net/?retryWrites=true&w=majority"
  JWT_SECRET= "LsI4Sc5+hfvmgvIPq7RUzyP2xfLi+Witic49FIQ4sX1jfZ3xEdfRvjJb9AIP5Drie3DZm6RKVB+khZ1e1kWpcw=="
  PORT= "4000"
