apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: two-tier
  labels:
    app: backend

type: Opaque
stringData:
  PORT: "4000"
  MONGO_DB: "mongodb+srv://konnecthere:nani0763@konnectcluster.iybsjhf.mongodb.net/?retryWrites=true&w=majority" 
  JWT_SECRET: "O8wfC7hZHnlNbB3xUrmuKEzCCYPaM4n41hH7wPp6tQZk7Ftk94t60qSoQXa9J/I6oe3ElupY5v2Vy9Vl0EBG4g=="
