apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: two-tier
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  type: ClusterIP
